apiVersion: v1
kind: Service
metadata:
  name: transaction-service-db
  labels:
    app: transaction-service
spec:
  ports:
  - port: 5432
  selector:
    app: transaction-service
    tier: postgresql
  clusterIP: None
